#!/usr/bin/env bash

USER=neuroidss
NAME=gcc-arm-none-eabi-ubuntu

docker manifest create \
  $USER/$NAME:latest \
  $USER/$NAME:amd64-latest \
  $USER/$NAME:arm64-latest \
  $USER/$NAME:arm-latest --amend
docker manifest annotate $USER/$NAME:latest  $USER/$NAME:amd64-latest --os linux --arch amd64
#docker manifest annotate $USER/$NAME:latest  $USER/$NAME:amd64-latest --os linux --arch amd64
docker manifest annotate $USER/$NAME:latest  $USER/$NAME:arm64-latest --os linux --arch arm64
#docker manifest annotate $USER/$NAME:latest  $USER/$NAME:arm64-latest --os linux --arch arm64 --variant v8
docker manifest annotate $USER/$NAME:latest  $USER/$NAME:arm-latest --os linux --arch arm
#docker manifest annotate $USER/$NAME:latest  $USER/$NAME:arm-latest --os linux --arch arm --variant v7
docker manifest push --purge $USER/$NAME:latest
